# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('champs', '0011_match'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='champ_id',
            new_name='champId',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='champ_level',
            new_name='champLevel',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='champ_name',
            new_name='champName',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='double_kills',
            new_name='doubleKills',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='first_blood_assist',
            new_name='firstBloodAssist',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='first_blood_kill',
            new_name='firstBloodKill',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='first_inhibitor_assist',
            new_name='firstInhibitorAssist',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='first_inhibitor_kill',
            new_name='firstInhibitorKill',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='first_tower_assist',
            new_name='firstTowerAssist',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='first_tower_kill',
            new_name='firstTowerKill',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='gold_earned',
            new_name='goldEarned',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='gold_spent',
            new_name='goldSpent',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='inhibitor_kills',
            new_name='inhibitorKills',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='killing_sprees',
            new_name='killingSprees',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='largest_critical_strike',
            new_name='largestCriticalStrike',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='largest_killing_spree',
            new_name='largestKillingSpree',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='largest_multi_kill',
            new_name='largestMultiKill',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='league_name',
            new_name='leagueName',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='magic_damage_dealt',
            new_name='magicDamageDealt',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='magic_damage_dealt_to_champions',
            new_name='magicDamageDealtToChampions',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='magic_damage_taken',
            new_name='magicDamageTaken',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='match_id',
            new_name='matchId',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='match_version',
            new_name='matchVersion',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='minions_killed',
            new_name='minionsKilled',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='neutral_minions_killed',
            new_name='neutralMinionsKilled',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='neutral_minions_killed_enemy_jungle',
            new_name='neutralMinionsKilledEnemyJungle',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='neutral_minions_killed_team_jungle',
            new_name='neutralMinionsKilledTeamJungle',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='penta_kills',
            new_name='pentaKills',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='physical_damage_dealt',
            new_name='physicalDamageDealt',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='physical_damage_dealt_to_champions',
            new_name='physicalDamageDealtToChampions',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='physical_damage_taken',
            new_name='physicalDamageTaken',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='quadra_kills',
            new_name='quadraKills',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='sight_wards_bought_in_game',
            new_name='sightWardsBoughtInGame',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='smart_role_name',
            new_name='smartRoleName',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='summoner_id',
            new_name='summonerId',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='total_damage_dealt',
            new_name='totalDamageDealt',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='total_damage_dealt_to_champions',
            new_name='totalDamageDealtToChampions',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='total_damage_taken',
            new_name='totalDamageTaken',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='total_heal',
            new_name='totalHeal',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='total_time_crowd_control_dealt',
            new_name='totalTimeCrowdControlDealt',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='total_units_healed',
            new_name='totalUnitsHealed',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='tower_kills',
            new_name='towerKills',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='triple_kills',
            new_name='tripleKills',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='true_damage_dealt',
            new_name='trueDamageDealt',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='true_damage_taken',
            new_name='trueDamageDealtToChampions',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='true_damage_dealt_to_champions',
            new_name='trueDamageTaken',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='unreal_kills',
            new_name='unrealKills',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='vision_wards_bought_in_game',
            new_name='visionWardsBoughtInGame',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='wards_killed',
            new_name='wardsKilled',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='wards_placed',
            new_name='wardsPlaced',
        ),
    ]
