# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('champs', '0026_auto_20150924_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemset',
            name='champ',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='matchCreation',
            new_name='match_creation',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='matchDuration',
            new_name='match_duration',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='matchId',
            new_name='match_id',
        ),
        migrations.RenameField(
            model_name='statset',
            old_name='champLevel',
            new_name='champ_level',
        ),
        migrations.RenameField(
            model_name='statset',
            old_name='doubleKills',
            new_name='double_kills',
        ),
        migrations.RenameField(
            model_name='statset',
            old_name='firstBloodAssist',
            new_name='firstBlood_assist',
        ),
        migrations.RenameField(
            model_name='statset',
            old_name='firstInhibitorAssist',
            new_name='firstBlood_kill',
        ),
        migrations.RenameField(
            model_name='statset',
            old_name='firstBloodKill',
            new_name='firstInhibitor_assist',
        ),
        migrations.RenameField(
            model_name='statset',
            old_name='firstInhibitorKill',
            new_name='firstInhibitor_kill',
        ),
        migrations.RenameField(
            model_name='statset',
            old_name='firstTowerAssist',
            new_name='first_tower_assist',
        ),
        migrations.RenameField(
            model_name='statset',
            old_name='firstTowerKill',
            new_name='first_tower_kill',
        ),
        migrations.RenameField(
            model_name='statset',
            old_name='goldEarned',
            new_name='gold_earned',
        ),
        migrations.RenameField(
            model_name='statset',
            old_name='inhibitorKills',
            new_name='gold_spent',
        ),
        migrations.RenameField(
            model_name='statset',
            old_name='goldSpent',
            new_name='inhibitor_kills',
        ),
        migrations.RenameField(
            model_name='statset',
            old_name='item0',
            new_name='item_0',
        ),
        migrations.RenameField(
            model_name='statset',
            old_name='item1',
            new_name='item_1',
        ),
        migrations.RenameField(
            model_name='statset',
            old_name='item3',
            new_name='item_2',
        ),
        migrations.RenameField(
            model_name='statset',
            old_name='item2',
            new_name='item_3',
        ),
        migrations.RenameField(
            model_name='statset',
            old_name='item4',
            new_name='item_4',
        ),
        migrations.RenameField(
            model_name='statset',
            old_name='item5',
            new_name='item_5',
        ),
        migrations.RenameField(
            model_name='statset',
            old_name='killingSprees',
            new_name='item_6',
        ),
        migrations.RenameField(
            model_name='statset',
            old_name='item6',
            new_name='killing_sprees',
        ),
        migrations.RenameField(
            model_name='statset',
            old_name='largestCriticalStrike',
            new_name='largest_critical_strike',
        ),
        migrations.RenameField(
            model_name='statset',
            old_name='largestKillingSpree',
            new_name='largest_killing_spree',
        ),
        migrations.RenameField(
            model_name='statset',
            old_name='magicDamageDealt',
            new_name='largest_multi_kill',
        ),
        migrations.RenameField(
            model_name='statset',
            old_name='largestMultiKill',
            new_name='magic_damage_dealt',
        ),
        migrations.RenameField(
            model_name='statset',
            old_name='magicDamageDealtToChampions',
            new_name='magic_damage_dealt_to_champions',
        ),
        migrations.RenameField(
            model_name='statset',
            old_name='magicDamageTaken',
            new_name='magic_damage_taken',
        ),
        migrations.RenameField(
            model_name='statset',
            old_name='neutralMinionsKilled',
            new_name='minions_killed',
        ),
        migrations.RenameField(
            model_name='statset',
            old_name='minionsKilled',
            new_name='neutral_minions_killed',
        ),
        migrations.RenameField(
            model_name='statset',
            old_name='neutralMinionsKilledEnemyJungle',
            new_name='neutral_minions_killed_enemy_jungle',
        ),
        migrations.RenameField(
            model_name='statset',
            old_name='pentaKills',
            new_name='neutral_minions_killed_team_jungle',
        ),
        migrations.RenameField(
            model_name='statset',
            old_name='neutralMinionsKilledTeamJungle',
            new_name='penta_kills',
        ),
        migrations.RenameField(
            model_name='statset',
            old_name='physicalDamageDealt',
            new_name='physical_damage_dealt',
        ),
        migrations.RenameField(
            model_name='statset',
            old_name='physicalDamageTaken',
            new_name='physical_damage_dealt_to_champions',
        ),
        migrations.RenameField(
            model_name='statset',
            old_name='physicalDamageDealtToChampions',
            new_name='physical_damage_taken',
        ),
        migrations.RenameField(
            model_name='statset',
            old_name='quadraKills',
            new_name='quadra_kills',
        ),
        migrations.RenameField(
            model_name='statset',
            old_name='totalDamageDealt',
            new_name='sight_wards_bought_in_game',
        ),
        migrations.RenameField(
            model_name='statset',
            old_name='statsetId',
            new_name='statset_id',
        ),
        migrations.RenameField(
            model_name='statset',
            old_name='sightWardsBoughtInGame',
            new_name='total_damage_dealt',
        ),
        migrations.RenameField(
            model_name='statset',
            old_name='totalDamageTaken',
            new_name='total_damage_dealt_to_champions',
        ),
        migrations.RenameField(
            model_name='statset',
            old_name='totalDamageDealtToChampions',
            new_name='total_damage_taken',
        ),
        migrations.RenameField(
            model_name='statset',
            old_name='totalHeal',
            new_name='total_heal',
        ),
        migrations.RenameField(
            model_name='statset',
            old_name='totalTimeCrowdControlDealt',
            new_name='total_time_crowd_control_dealt',
        ),
        migrations.RenameField(
            model_name='statset',
            old_name='towerKills',
            new_name='total_units_healed',
        ),
        migrations.RenameField(
            model_name='statset',
            old_name='totalUnitsHealed',
            new_name='tower_kills',
        ),
        migrations.RenameField(
            model_name='statset',
            old_name='tripleKills',
            new_name='triple_kills',
        ),
        migrations.RenameField(
            model_name='statset',
            old_name='trueDamageDealt',
            new_name='true_damage_dealt',
        ),
        migrations.RenameField(
            model_name='statset',
            old_name='trueDamageTaken',
            new_name='true_damage_dealt_to_champions',
        ),
        migrations.RenameField(
            model_name='statset',
            old_name='trueDamageDealtToChampions',
            new_name='true_damage_taken',
        ),
        migrations.RenameField(
            model_name='statset',
            old_name='unrealKills',
            new_name='unreal_kills',
        ),
        migrations.RenameField(
            model_name='statset',
            old_name='wardsKilled',
            new_name='vision_wards_bought_in_game',
        ),
        migrations.RenameField(
            model_name='statset',
            old_name='visionWardsBoughtInGame',
            new_name='wards_killed',
        ),
        migrations.RenameField(
            model_name='statset',
            old_name='wardsPlaced',
            new_name='wards_placed',
        ),
        migrations.DeleteModel(
            name='ItemSet',
        ),
    ]
